POST http://127.0.0.1:20000/register
Content-Type: application/json
Subscribe-Key: HNsk97ujaslo

{
    "email":"souksavanh.public@gmail.com"
}

###
POST http://127.0.0.1:20000/verifyOtp
Content-Type: application/json
Subscribe-Key: HNsk97ujaslo

{
    "email":"souksavanh.public@gmail.com",
    "otp":"879385"
}